file(MAKE_DIRECTORY "${WORK}")
set(count 0)
function(run_case name expected fragment)
    execute_process(COMMAND "${APP}" ${ARGN} RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${code}" STREQUAL "${expected}")
        message(FATAL_ERROR "${name}: exit=${code}\n${out}\n${err}")
    endif()
    string(FIND "${out}${err}" "${fragment}" found)
    if(found LESS 0)
        message(FATAL_ERROR "${name}: missing ${fragment}\n${out}\n${err}")
    endif()
    math(EXPR next "${count} + 1")
    set(count ${next} PARENT_SCOPE)
    message(STATUS "PASS: ${name}")
endfunction()
set(base --cache-size 64 --block-size 16 --associativity 1)
run_case(help 0 "Usage:" --help)
run_case(sample 0 "Hit rate:          40.00%" ${base} --trace "${SOURCE}/data/sample_trace.txt")
run_case(locality 0 "Hit rate:          83.33%" --cache-size 64 --block-size 16 --associativity 2 --trace "${SOURCE}/data/locality_trace.txt")
run_case(conflict_direct 0 "Evictions:         5" ${base} --trace "${SOURCE}/data/conflict_trace.txt")
run_case(conflict_two_way 0 "Hit rate:          66.67%" --cache-size 64 --block-size 16 --associativity 2 --trace "${SOURCE}/data/conflict_trace.txt")
run_case(bad_capacity 1 "divisible" --cache-size 60 --block-size 16 --associativity 1 --trace unused)
run_case(bad_block 1 "power of two" --cache-size 60 --block-size 3 --associativity 1 --trace unused)
run_case(bad_ways 1 "cannot exceed" --cache-size 64 --block-size 16 --associativity 8 --trace unused)
run_case(bad_sets 1 "Number of sets" --cache-size 48 --block-size 16 --associativity 1 --trace unused)
run_case(negative 1 "positive decimal" --cache-size -1 --block-size 16 --associativity 1 --trace unused)
run_case(overflow 1 "positive decimal" --cache-size 999999999999999999999999 --block-size 16 --associativity 1 --trace unused)
run_case(unknown 1 "unknown" --nope 1)
run_case(missing_value 1 "incomplete" --trace)
run_case(missing_required 1 "required" --cache-size 64)
run_case(duplicate 1 "duplicate" ${base} --cache-size 64)
run_case(missing_file 1 "cannot open" ${base} --trace "${WORK}/not-present.txt")
file(WRITE "${WORK}/empty.txt" "")
run_case(empty 0 "Hit rate:          N/A" ${base} --trace "${WORK}/empty.txt")
string(REPEAT "x" 2000 long)
file(WRITE "${WORK}/bad.txt" "R 0\n${long}\nX 3\nR -1\nW 4\nR 0xffffffffffffffff")
run_case(bad_lines 0 "Total accesses:    3" ${base} --trace "${WORK}/bad.txt")
run_case(line_numbers 0 "Warning: line 2:" ${base} --trace "${WORK}/bad.txt")
file(REMOVE "${WORK}/report.txt")
run_case(report 0 "Total accesses:    10" ${base} --trace "${SOURCE}/data/sample_trace.txt" --report "${WORK}/report.txt")
file(READ "${WORK}/report.txt" report)
foreach(fragment "Simulation time:" "Trace file: sample_trace.txt" "40.00%" "Misses:            6" "Evictions:         2")
    string(FIND "${report}" "${fragment}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Report missing ${fragment}")
    endif()
endforeach()
run_case(report_existing 1 "new filename" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/report.txt")
run_case(report_parent 1 "parent directory" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/missing-dir/report.txt")
run_case(report_same_trace 1 "paths must differ" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/empty.txt")
file(WRITE "${WORK}/all-bad.txt" "W -1\nR 0x\n")
run_case(all_bad 0 "No valid accesses." ${base} --trace "${WORK}/all-bad.txt")
message(STATUS "${count} CLI tests passed")
