file(MAKE_DIRECTORY "${WORK}")
set(count 0)
function(run_case name expected fragment)
    execute_process(COMMAND "${APP}" ${ARGN} RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${code}" STREQUAL "${expected}")
        message(FATAL_ERROR "${name}: exit=${code}\n${out}\n${err}")
    endif()
    string(FIND "${out}${err}" "${fragment}" found)
    if(found LESS 0)
        message(FATAL_ERROR "${name}: missing ${fragment}\n${out}\n${err}")
    endif()
    math(EXPR next "${count} + 1")
    set(count ${next} PARENT_SCOPE)
    message(STATUS "PASS: ${name}")
endfunction()
set(base --cache-size 64 --block-size 16 --associativity 1)
run_case(help 0 "Usage:" --help)
run_case(sample 0 "Hit rate:          40.00%" ${base} --trace "${SOURCE}/data/sample_trace.txt")
run_case(locality 0 "Hit rate:          83.33%" --cache-size 64 --block-size 16 --associativity 2 --trace "${SOURCE}/data/locality_trace.txt")
run_case(conflict_direct 0 "Evictions:         5" ${base} --trace "${SOURCE}/data/conflict_trace.txt")
run_case(conflict_two_way 0 "Hit rate:          66.67%" --cache-size 64 --block-size 16 --associativity 2 --trace "${SOURCE}/data/conflict_trace.txt")
run_case(bad_capacity 1 "divisible" --cache-size 60 --block-size 16 --associativity 1 --trace unused)
run_case(bad_block 1 "power of two" --cache-size 60 --block-size 3 --associativity 1 --trace unused)
run_case(bad_ways 1 "cannot exceed" --cache-size 64 --block-size 16 --associativity 8 --trace unused)
run_case(bad_sets 1 "Number of sets" --cache-size 48 --block-size 16 --associativity 1 --trace unused)
run_case(negative 1 "positive decimal" --cache-size -1 --block-size 16 --associativity 1 --trace unused)
run_case(overflow 1 "positive decimal" --cache-size 999999999999999999999999 --block-size 16 --associativity 1 --trace unused)
run_case(unknown 1 "unknown" --nope 1)
run_case(missing_value 1 "incomplete" --trace)
run_case(missing_required 1 "required" --cache-size 64)
run_case(duplicate 1 "duplicate" ${base} --cache-size 64)
run_case(missing_file 1 "cannot open" ${base} --trace "${WORK}/not-present.txt")
file(WRITE "${WORK}/empty.txt" "")
run_case(empty 0 "Hit rate:          N/A" ${base} --trace "${WORK}/empty.txt")
string(REPEAT "x" 2000 long)
file(WRITE "${WORK}/bad.txt" "R 0\n${long}\nX 3\nR -1\nW 4\nR 0xffffffffffffffff")
run_case(bad_lines 0 "Total accesses:    3" ${base} --trace "${WORK}/bad.txt")
run_case(line_numbers 0 "Warning: line 2:" ${base} --trace "${WORK}/bad.txt")
file(REMOVE "${WORK}/report.txt")
run_case(report 0 "Total accesses:    10" ${base} --trace "${SOURCE}/data/sample_trace.txt" --report "${WORK}/report.txt")
file(READ "${WORK}/report.txt" report)
foreach(fragment "Simulation time:" "Trace file: sample_trace.txt" "40.00%" "Misses:            6" "Evictions:         2")
    string(FIND "${report}" "${fragment}" found)
    if(found LESS 0)
        message(FATAL_ERROR "Report missing ${fragment}")
    endif()
endforeach()
run_case(report_existing 1 "new filename" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/report.txt")
run_case(report_parent 1 "parent directory" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/missing-dir/report.txt")
run_case(report_same_trace 1 "paths must differ" ${base} --trace "${WORK}/empty.txt" --report "${WORK}/empty.txt")
file(WRITE "${WORK}/all-bad.txt" "W -1\nR 0x\n")
run_case(all_bad 0 "No valid accesses." ${base} --trace "${WORK}/all-bad.txt")
set(policy_config --sets 4 --ways 2 --block-size 16)
set(difference "${SOURCE}/data/policy_difference.trace")
run_case(default_lru 0 "Replacement policy: LRU" ${policy_config} "${difference}")
run_case(explicit_lru 0 "Hit rate:          40.00%" ${policy_config} --policy lru "${difference}")
run_case(explicit_fifo 0 "Hit rate:          20.00%" ${policy_config} --policy fifo "${difference}")
run_case(invalid_policy 1 "policy must" ${policy_config} --policy random "${difference}")
run_case(uppercase_policy 1 "lowercase" ${policy_config} --policy FIFO "${difference}")
run_case(missing_policy 1 "incomplete" ${policy_config} "${difference}" --policy)
run_case(duplicate_policy 1 "duplicate" ${policy_config} "${difference}" --policy fifo --policy lru)
run_case(capacity_and_sets 1 "not both" ${policy_config} --cache-size 128 "${difference}")
run_case(sets_overflow 1 "overflow" --sets 18446744073709551615 --ways 2 --block-size 16 "${difference}")
run_case(compare_missing_trace 1 "cannot open" ${policy_config} --compare-policies "${WORK}/absent.trace")
run_case(compare_policy_conflict 1 "comparison" ${policy_config} --compare-policies --policy fifo "${difference}")
run_case(csv_requires_compare 1 "requires comparison" ${policy_config} --csv unused "${difference}")
run_case(compare_empty 0 "N/A" ${policy_config} --compare-policies "${WORK}/empty.txt")
run_case(compare_direct_note 0 "cannot affect" --sets 4 --ways 1 --block-size 16 --compare-policies "${difference}")

function(compare_csv name trace ways expected)
    set(path "${WORK}/${name}.csv")
    file(REMOVE "${path}")
    run_case(${name} 0 "FIFO" --sets 4 --ways ${ways} --block-size 16 --compare-policies "${trace}" --csv "${path}")
    file(READ "${path}" actual)
    set(header "policy,accesses,hits,misses,evictions,hit_rate\n")
    if(NOT actual STREQUAL "${header}${expected}")
        message(FATAL_ERROR "${name}: unexpected CSV: ${actual}")
    endif()
    set(count ${count} PARENT_SCOPE)
endfunction()
compare_csv(lru_advantage "${difference}" 2 "LRU,5,2,3,1,0.400000000\nFIFO,5,1,4,2,0.200000000\n")
compare_csv(fifo_advantage "${SOURCE}/data/policy_fifo_advantage.trace" 2 "LRU,5,1,4,2,0.200000000\nFIFO,5,2,3,1,0.400000000\n")
compare_csv(equal_cold_caches "${SOURCE}/data/policy_equal.trace" 2 "LRU,4,2,2,0,0.500000000\nFIFO,4,2,2,0,0.500000000\n")
compare_csv(direct_equal "${difference}" 1 "LRU,5,0,5,4,0.000000000\nFIFO,5,0,5,4,0.000000000\n")
compare_csv(empty_csv "${WORK}/empty.txt" 2 "LRU,0,0,0,0,\nFIFO,0,0,0,0,\n")
file(WRITE "${WORK}/single.trace" "R 0\n")
compare_csv(single_miss "${WORK}/single.trace" 2 "LRU,1,0,1,0,0.000000000\nFIFO,1,0,1,0,0.000000000\n")
run_case(csv_existing 1 "new filename" ${policy_config} --compare-policies "${difference}" --csv "${WORK}/lru_advantage.csv")
run_case(csv_same_trace 1 "paths must differ" ${policy_config} --compare-policies "${difference}" --csv "${difference}")
file(REMOVE "${WORK}/fifo-report.txt")
run_case(fifo_report 0 "20.00%" ${policy_config} --policy fifo "${difference}" --report "${WORK}/fifo-report.txt")
file(READ "${WORK}/fifo-report.txt" fifo_report)
if(NOT fifo_report MATCHES "FIFO")
    message(FATAL_ERROR "FIFO report mislabels policy")
endif()
message(STATUS "${count} CLI tests passed")
